# Generated by Django 4.2 on 2026-05-17 04:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='ID of the user from User & Auth Service', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('HOSPITAL', 'Hospital'), ('NOTARY', 'Notary'), ('BANK', 'Bank'), ('MANUFACTURER', 'Manufacturer')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=10)),
                ('approved_by', models.UUIDField(blank=True, help_text='ID of the admin who approved or rejected', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'institutions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='institution_documents/')),
                ('document_type', models.CharField(choices=[('ACCREDITATION', 'Accreditation Certificate'), ('REGISTRATION', 'Registration Paper'), ('LICENSE', 'Operating License'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='institution_app.institution')),
            ],
            options={
                'db_table': 'institution_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
