# Generated by Django 4.2 on 2026-05-18 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_hash', models.CharField(help_text='SHA-256 hash of the item details', max_length=64, unique=True)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Certificate'), ('PHARMA', 'Pharmaceutical Product'), ('DOCUMENT', 'Official Document'), ('CURRENCY', 'Currency / Banknote')], max_length=20)),
                ('issuer_id', models.CharField(help_text='UUID of the issuer from the auth service', max_length=255)),
                ('issuer_name', models.CharField(help_text='Human-readable institution name', max_length=255)),
                ('tx_hash', models.CharField(blank=True, help_text='Ethereum transaction hash returned by Ganache', max_length=255)),
                ('status', models.CharField(choices=[('STORED', 'Stored on blockchain'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending — blockchain temporarily unreachable')], default='STORED', max_length=10)),
                ('revoke_reason', models.TextField(blank=True, help_text='Reason for revocation if status is REVOKED')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blockchain_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
