# Generated by Django 4.2 on 2026-05-18 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(help_text='ID of the suspicious item')),
                ('issuer_id', models.UUIDField(blank=True, help_text='ID of the issuer who registered the item', null=True)),
                ('verification_count', models.IntegerField(help_text='Number of verifications in the time window')),
                ('window_start', models.DateTimeField(help_text='Start of the suspicious time window')),
                ('window_end', models.DateTimeField(help_text='End of the suspicious time window')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('resolved_by', models.UUIDField(blank=True, help_text='ID of the admin who resolved this flag', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'fraud_flags',
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.UUIDField(blank=True, help_text='ID of the item being verified', null=True)),
                ('issuer_id', models.UUIDField(blank=True, help_text='ID of the issuer who registered the item', null=True)),
                ('method', models.CharField(choices=[('QR', 'QR Code Scan'), ('SERIAL', 'Serial Number'), ('SIGNATURE', 'Digital Signature'), ('OCR', 'OCR Photo Scan'), ('WATERMARK', 'Watermark Detection')], max_length=10)),
                ('result', models.CharField(choices=[('AUTHENTIC', 'Authentic'), ('NOT_AUTHENTIC', 'Not Authentic'), ('UNVERIFIABLE', 'Unverifiable')], max_length=15)),
                ('input_data', models.TextField(blank=True, help_text='The QR data, serial number, or other input used')),
                ('verifier_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verification_logs',
                'ordering': ['-verified_at'],
            },
        ),
    ]
